global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['cadvisor:8080', 'localhost:9090']
        labels:
          group: 'identidock-system'
